#ifndef _KEYWORDS_H
#define _KEYWORDS_H

typedef enum enPathField{
CMD_DEVICE,CMD_SYSTEM,CMD_ANTENNA,CMD_GPS,CMD_RADIO,CMD_NETWORK,CMD_DISK,CMD_EXTERNAL,CMD_BLUETOOTH,CMD_ENABLE,CMD_CONNECTED,CMD_WIFI,CMD_SCAN,CMD_GPRS,\
CMD_NTRIP,CMD_RECORD,CMD_PORTS,CMD_SELF_CHECK,CMD_STARTBASE,CMD_STOPBASE,CMD_RESET,CMD_POWEROFF,CMD_POWER_LEVEL,CMD_STARTRECORD,CMD_STOPRECORD,\
CMD_CONNECT,CMD_DISCONNECT,CMD_WAN,CMD_MOUNTMSD,CMD_CLEANLOG,CMD_FTP,CMD_PUSH,CMD_GEO,CMD_TEST,CMD_EMAIL,CMD_SMS,CMD_HTTP_PORT,CMD_DEFAULT,CMD_NTRIP_CLIENT,CMD_CONNECTION,CMD_DELETE,\
CMD_SECURITY_CODE,CMD_DEVINFO,CMD_REGI,CMD_SOCKET0_RAW,CMD_SOCKET1_RAW,CMD_SOCKET2_RAW,CMD_UPDATE,CMD_MODE,CMD_POWER,CMD_CHANNEL,CMD_FREQUENCY,CMD_UPGRADE,CMD_FRESET,CMD_FORMAT,\
CMD_STATUS,CMD_UCSHELL,CMD_REMOTE,CMD_PRIORITY,CMD_DNS1,CMD_DNAT,CMD_SNAT,CMD_NETDATA,CMD_SESSION,CMD_ONCHANGED,CMD_RESTARTBASE,CMD_DISABLEPRN,CMD_ENABLEALLPRN,CMD_NTP,\
CMD_TIMEZONE,CMD_TZID,CMD_DYNAMIC_DNS,CMD_IP,CMD_VPN,CMD_GCOMPRESS,CMD_CONFIGSET,CMD_SAVE,CMD_RESTORE,CMD_NARI,\
CMD_END_OF_PATHFIELD}PATH_FIELD;//


int GetEnumFromKeyword(char * key);

#endif
